name: xmpp_defi

description: xmpp-defi is a library for decentralized finance written in Dart for crossplatform applications including web apps.

version: 0.1.2

homepage: communitychest.io

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  xmpp_stone: ^0.4.0-dev.1
  cryptography: ^2.0.2
  universal_io: ^2.0.4
  libsignal_protocol_dart: ^0.5.5

dev_dependencies:
  test: ^1.18.2
  mockito: ^5.0.16
