name: xmpp_defi

description: "XMPP Defi is library for decentralized finance written in Dart."

version: 0.1.1

homepage: https://communitychest.io

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  pointycastle: ^3.3.1
  xmpp_stone: ^0.4.0-dev.1
