name: xmpp_defi

description: >-
  A library for decentralized finance written in Dart for crossplatform applications including web apps.

repository: github.com/comchest/xmpp-defi

version: 0.3.0

homepage: communitychest.io

environment:
  sdk: '>=2.17.0 < 3.0.0'

dependencies:
  xmpp_stone: ^0.4.3-dev.1
  cryptography: ^2.0.5
  universal_io: ^2.0.4
  libsignal_protocol_dart: ^0.5.6
  bs58: ^1.0.2
  bip39: ^1.0.6
  drift: ^1.6.0
  path_provider: ^2.0.9
  path: ^1.8.1
  web_socket_channel: ^2.1.0

dev_dependencies:
#  test: ^1.21.1
#  mockito: ^5.0.16
  drift_dev: ^1.6.0
  build_runner: ^2.1.10
