name: xmpp_defi

description: >-
  A library for decentralized finance written in Dart for cross-platform applications including web apps.

repository: github.com/comchest/xmpp-defi

version: 0.1.3

homepage: communitychest.io

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  xmpp_stone: ^0.4.3-dev.1
  cryptography: ^2.0.5
  universal_io: ^2.0.4
  libsignal_protocol_dart: ^0.5.6
  bs58: ^1.0.2
  bip39: ^1.0.6

dev_dependencies:
  test: ^1.18.2
  mockito: ^5.0.16
